#!/bin/bash
if [ "$SCRAMRT_SET" = "" ] ; then
  export SCRAMV3_BACKUP_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH=""
fi
#export SCRAMV3_BACKUP_PYTHONPATH=${PYTHONPATH}
PYTHONPATH="" $(dirname $0)/scram.py "$@"
