#!/bin/bash
cmd_python3=$(which python3)
if [ "${SCRAMRT_SET}" = "" ] ; then
  export SCRAMV3_BACKUP_LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
  export LD_LIBRARY_PATH=""
  cmd_python3=$(env -i command -v python3)
fi
SCRAM_RUNTIME_TYPE="" PYTHONPATH="" ${cmd_python3} $(dirname $0)/scram.py "$@"
